[build]
  publish = "_site"
  # Allows overriding metadata.json via env var
  command = "[ \"$METADATA_JSON\" ] && echo $METADATA_JSON > _data/metadata.json; npm run build-ci"
  functions = "functions/"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/img/generated", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"
